# Generated by Django 5.1.2 on 2025-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_alter_product_qr_code_alter_product_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
