# Generated by Django 5.1.2 on 2025-10-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0003_alter_product_qr_code_alter_product_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
